### ISSUE TITLE
Fix pulldown menu width

### ISSUE THREAD

**Issue by aghosh15** [samueljrush/bqbl#43]
All of the weekly pages have a dropdown menu on the top left for the selected week. When this menu is clicked, the width of the menu is too narrow for the text "Week" and the current week to both fit, so the menu is twice the length it needs to be and looks like shit.

Pls fix

**Comment by samueljrush** [comment]
I'm confused. The menu *should* be on the top right, not the top left, and it displays reasonably on both my desktop monitor and phone. Not saying it's WAI, but can you tell me what device you are using and attach a screenshot to clarify?

**Comment by aghosh15** [comment]
Whoops, I meant top left. Desktop Win 7, using Chrome. I'm attaching the screenshot.

FWIW it also works fine on my phone.

![pulldown bug](https://cloud.githubusercontent.com/assets/8681838/9772597/325a8c52-570b-11e5-8b7d-874c705a98a8.png)

**Comment by samueljrush** [comment]
Oh, this is trivial to fix. Done.
